title: Security Research Lab
description: Penetration testing notes and security research
author: fran
url: "https://goodmorninggoodbye.github.io/security-research-blog"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections for organizing content
collections:
  writeups:
    output: true
    permalink: /:collection/:name/
